name: Manual trigger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        required: true
        default: 'main'

jobs:
  manual-trigger:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Print branch
        run: echo "Working for branch ${{ github.event.inputs.branch }}"
