name: CI/CD with manual trigger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        required: true
        default: 'main'

jobs:
  manual-ci-cd-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tests
      run: echo "Tests passed"
  manual-ci-cd-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tests
      run: echo "Linting passed"
  manual-ci-cd-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - manual-ci-cd-test
      - manual-ci-cd-lint
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying ${{ github.event.inputs.branch }}"
