name: Multi-job CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  multi-job-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tests
      run: echo "Tests passed"
  multi-job-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tests
      run: echo "Linting passed"
